name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'

      - name: Create Clean Project and Restore Code
        run: |
          mkdir -p backup_lib backup_assets
          cp -r lib/* backup_lib/ 2>/dev/null || true
          cp -r assets/* backup_assets/ 2>/dev/null || true
          flutter create mysurveyapp --org com.mysurvey --platforms=android
          cd mysurveyapp
          rm -rf lib/*
          cp -r ../backup_lib/* lib/ 2>/dev/null || true
          cp -r ../backup_assets/* assets/ 2>/dev/null || true
          flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: mysurveyapp/build/app/outputs/flutter-apk/app-debug.apk
